import {
    AiFlowGenerationStatus,
    FlowActionType,
    FlowStatus,
    FlowTriggerType,
    FlowVersionState,
    GeneratedStepRequirement,
    PopulatedFlow,
    WORKFLOW_PLAN_VERSION,
    WorkflowStepKind,
    WorkflowTriggerKind,
} from '@activepieces/shared'
import { FastifyInstance } from 'fastify'
import { StatusCodes } from 'http-status-codes'
import { db } from '../../../helpers/db'
import { createMockConnection } from '../../../helpers/mocks'
import { resolverPieces } from '../../../helpers/resolver-pieces'
import { createTestContext, TestContext } from '../../../helpers/test-context'
import { setupTestEnvironment, teardownTestEnvironment } from '../../../helpers/test-setup'

const TELEGRAM = '@activepieces/piece-telegram-bot'
const SHEETS = '@activepieces/piece-google-sheets'
const SLACK = '@activepieces/piece-slack'
const HTTP = '@activepieces/piece-http'
const SCHEDULE = '@activepieces/piece-schedule'

let app: FastifyInstance | null = null

beforeAll(async () => {
    app = await setupTestEnvironment()
})

afterAll(async () => {
    await teardownTestEnvironment()
})

async function seeded(): Promise<TestContext> {
    const ctx = await createTestContext(app!)
    await resolverPieces.seed({ platformId: ctx.platform.id })
    return ctx
}

async function connect({ ctx, pieceName, displayName }: { ctx: TestContext, pieceName: string, displayName: string }): Promise<string> {
    const connection = createMockConnection({ projectIds: [ctx.project.id], platformId: ctx.platform.id, pieceName, displayName }, ctx.user.id)
    await db.save('app_connection', connection)
    return connection.externalId
}

function plan({ name, steps, cronExpression = '0 7 * * *' }: { name: string, steps: PlanStep[], cronExpression?: string }) {
    return {
        version: WORKFLOW_PLAN_VERSION,
        name,
        description: 'Generated by a test',
        trigger: {
            kind: WorkflowTriggerKind.SCHEDULE,
            summary: 'Every day at 07:00',
            service: null,
            schedule: { cronExpression, timezone: 'Asia/Ulaanbaatar', description: 'every day at 07:00' },
        },
        steps,
    }
}

async function generate({ ctx, prompt, planBody }: { ctx: TestContext, prompt: string, planBody: unknown }) {
    const response = await ctx.post('/v1/ai-flow-builder/generate', { projectId: ctx.project.id, prompt, plan: planBody })
    expect(response?.statusCode).toBe(StatusCodes.OK)
    return response?.json()
}

async function openInBuilder({ ctx, flowId }: { ctx: TestContext, flowId: string }) {
    const response = await ctx.get(`/v1/flows/${flowId}`, { projectId: ctx.project.id })
    expect(response?.statusCode).toBe(StatusCodes.OK)
    return response?.json()
}

function stepChain(trigger: { name: string, nextAction?: { name: string, settings: Record<string, unknown>, nextAction?: unknown } }) {
    const names: string[] = []
    let current = trigger.nextAction
    while (current) {
        names.push(current.name)
        current = current.nextAction as typeof current
    }
    return names
}

const GOLD_PRICE_PLAN: PlanStep[] = [
    { id: 'fetch_price', kind: WorkflowStepKind.FETCH, summary: 'Send an HTTP request to the gold price API', service: 'web api', dependsOn: [] },
    { id: 'compute_change', kind: WorkflowStepKind.TRANSFORM, summary: 'Calculate the daily change', service: null, dependsOn: ['fetch_price'] },
    { id: 'notify', kind: WorkflowStepKind.OUTPUT, summary: 'Send the result as a Telegram message', service: 'chat', dependsOn: ['compute_change'] },
]

describe('Flow generation from a resolved plan', () => {
    it('builds the gold price flow: schedule, HTTP fetch, Telegram send', async () => {
        const ctx = await seeded()
        const telegramId = await connect({ ctx, pieceName: TELEGRAM, displayName: 'Telegram Personal' })

        const body = await generate({
            ctx,
            prompt: "Every day at 7 AM send me yesterday's gold price change on Telegram.",
            planBody: plan({ name: 'Daily gold price change', steps: GOLD_PRICE_PLAN }),
        })

        expect(body.status).toBe(AiFlowGenerationStatus.DRAFTED)
        const flow = await openInBuilder({ ctx, flowId: body.flowId })

        expect(flow.version.displayName).toBe('Daily gold price change')
        expect(flow.version.trigger.type).toBe(FlowTriggerType.PIECE)
        expect(flow.version.trigger.settings).toMatchObject({
            pieceName: SCHEDULE,
            triggerName: 'cron_expression',
            input: { cronExpression: '0 7 * * *', timezone: 'Asia/Ulaanbaatar' },
        })

        const first = flow.version.trigger.nextAction
        expect(first.type).toBe(FlowActionType.PIECE)
        expect(first.settings).toMatchObject({ pieceName: HTTP, actionName: 'send_request' })

        const second = first.nextAction
        expect(second.settings).toMatchObject({ pieceName: TELEGRAM, actionName: 'send_text_message' })
        expect(second.settings.input.auth).toBe(`{{connections['${telegramId}']}}`)
        expect(second.nextAction).toBeUndefined()
    })

    it('reports the transform step as needing no tool instead of inventing one', async () => {
        const ctx = await seeded()
        await connect({ ctx, pieceName: TELEGRAM, displayName: 'Telegram Personal' })

        const body = await generate({
            ctx,
            prompt: 'gold price',
            planBody: plan({ name: 'Daily gold price change', steps: GOLD_PRICE_PLAN }),
        })

        const transform = body.steps.find((step: { planStepId: string }) => step.planStepId === 'compute_change')
        expect(transform).toMatchObject({ pieceName: null, valid: true, requirements: [] })
        expect(body.steps.map((step: { planStepId: string | null }) => step.planStepId)).toEqual([null, 'fetch_price', 'compute_change', 'notify'])
    })

    it('translates a plan dependency into a real Activepieces step reference', async () => {
        const ctx = await seeded()
        await connect({ ctx, pieceName: TELEGRAM, displayName: 'Telegram Personal' })

        const body = await generate({
            ctx,
            prompt: 'gold price',
            planBody: plan({ name: 'Gold price', steps: GOLD_PRICE_PLAN }),
        })
        const flow = await openInBuilder({ ctx, flowId: body.flowId })

        const httpStepName = flow.version.trigger.nextAction.name
        const telegram = flow.version.trigger.nextAction.nextAction
        expect(telegram.settings.input.message).toBe(`{{${httpStepName}['output']}}`)
    })

    it('only ever writes property names the piece actually declares', async () => {
        const ctx = await seeded()
        await connect({ ctx, pieceName: TELEGRAM, displayName: 'Telegram Personal' })

        const body = await generate({ ctx, prompt: 'gold price', planBody: plan({ name: 'Gold price', steps: GOLD_PRICE_PLAN }) })
        const flow = await openInBuilder({ ctx, flowId: body.flowId })
        const pieces = await ctx.get('/v1/pieces/@activepieces/piece-telegram-bot', { projectId: ctx.project.id })

        const declared = new Set([...Object.keys(pieces?.json().actions.send_text_message.props), 'auth'])
        const written = Object.keys(flow.version.trigger.nextAction.nextAction.settings.input)
        expect(written.every((key) => declared.has(key))).toBe(true)
    })

    it('marks a missing connection as a requirement without failing the build', async () => {
        const ctx = await seeded()

        const body = await generate({ ctx, prompt: 'gold price', planBody: plan({ name: 'Gold price', steps: GOLD_PRICE_PLAN }) })

        expect(body.status).toBe(AiFlowGenerationStatus.DRAFTED)
        const telegram = body.steps.find((step: { pieceName: string }) => step.pieceName === TELEGRAM)
        expect(telegram.requirements).toContain(GeneratedStepRequirement.CONNECTION_MISSING)
        expect(telegram.valid).toBe(false)
        expect(telegram.connectionDisplayName).toBeNull()
    })

    it('reports a required input the builder must resolve rather than guessing a value', async () => {
        const ctx = await seeded()
        await connect({ ctx, pieceName: SHEETS, displayName: 'Sheets Work' })

        const body = await generate({
            ctx,
            prompt: 'rows',
            planBody: plan({
                name: 'Row sync',
                steps: [{ id: 'append', kind: WorkflowStepKind.OUTPUT, summary: 'Add the row to the Google Sheets spreadsheet', service: 'spreadsheet', dependsOn: [] }],
            }),
        })

        const step = body.steps.find((entry: { pieceName: string | null }) => entry.pieceName === SHEETS)
        expect(step.pieceName).toBe(SHEETS)
        expect(step.missingProperties).toContain('spreadsheetId')
        expect(step.requirements).toContain(GeneratedStepRequirement.REQUIRED_INPUT)
    })

    it('leaves the flow as an editable unpublished draft', async () => {
        const ctx = await seeded()

        const body = await generate({ ctx, prompt: 'gold price', planBody: plan({ name: 'Gold price', steps: GOLD_PRICE_PLAN }) })
        const flow = await openInBuilder({ ctx, flowId: body.flowId })

        expect(flow.status).toBe(FlowStatus.DISABLED)
        expect(flow.publishedVersionId).toBeNull()
        expect(flow.version.state).toBe(FlowVersionState.DRAFT)
    })

    it('keeps one draft version rather than one per step', async () => {
        const ctx = await seeded()

        const body = await generate({ ctx, prompt: 'gold price', planBody: plan({ name: 'Gold price', steps: GOLD_PRICE_PLAN }) })
        const versions = await ctx.get(`/v1/flows/${body.flowId}/versions`, { projectId: ctx.project.id })

        expect(versions?.json().data.filter((version: { state: string }) => version.state === FlowVersionState.DRAFT)).toHaveLength(1)
    })

    it('orders steps by their dependencies, not the order they were listed', async () => {
        const ctx = await seeded()
        await connect({ ctx, pieceName: SLACK, displayName: 'Slack Work' })

        const body = await generate({
            ctx,
            prompt: 'ordering',
            planBody: plan({
                name: 'Out of order',
                steps: [
                    { id: 'notify', kind: WorkflowStepKind.OUTPUT, summary: 'Post the summary to the Slack channel', service: 'chat', dependsOn: ['collect'] },
                    { id: 'collect', kind: WorkflowStepKind.FETCH, summary: 'Send an HTTP request to the reporting API', service: 'web api', dependsOn: [] },
                ],
            }),
        })
        const flow = await openInBuilder({ ctx, flowId: body.flowId })

        const chain = stepChain(flow.version.trigger)
        expect(chain).toHaveLength(2)
        expect(flow.version.trigger.nextAction.settings.pieceName).toBe(HTTP)
        expect(flow.version.trigger.nextAction.nextAction.settings.pieceName).toBe(SLACK)
    })

    it('still builds the rest when one step resolves to nothing', async () => {
        const ctx = await seeded()
        await connect({ ctx, pieceName: SLACK, displayName: 'Slack Work' })

        const body = await generate({
            ctx,
            prompt: 'partial',
            planBody: plan({
                name: 'Partial build',
                steps: [
                    { id: 'score', kind: WorkflowStepKind.TRANSFORM, summary: 'Score the claim with the actuarial mainframe model', service: 'mainframe', dependsOn: [] },
                    { id: 'notify', kind: WorkflowStepKind.OUTPUT, summary: 'Post the summary to the Slack channel', service: 'chat', dependsOn: ['score'] },
                ],
            }),
        })
        const flow = await openInBuilder({ ctx, flowId: body.flowId })

        const unresolved = body.steps.find((entry: { planStepId: string | null }) => entry.planStepId === 'score')
        expect(unresolved.requirements).toContain(GeneratedStepRequirement.NO_TOOL_RESOLVED)
        expect(stepChain(flow.version.trigger)).toHaveLength(1)
        expect(flow.version.trigger.nextAction.settings.pieceName).toBe(SLACK)
    })

    it('produces a flow the builder can decode, for every step shape it generates', async () => {
        const ctx = await seeded()
        await connect({ ctx, pieceName: TELEGRAM, displayName: 'Telegram Personal' })

        const body = await generate({
            ctx,
            prompt: 'gold price',
            planBody: plan({
                name: 'Mixed shapes',
                steps: [
                    ...GOLD_PRICE_PLAN,
                    { id: 'sheet', kind: WorkflowStepKind.OUTPUT, summary: 'Add the row to the Google Sheets spreadsheet', service: 'spreadsheet', dependsOn: ['notify'] },
                    { id: 'unknown', kind: WorkflowStepKind.TRANSFORM, summary: 'Score it with the mainframe model', service: 'mainframe', dependsOn: ['sheet'] },
                ],
            }),
        })
        const flow = await openInBuilder({ ctx, flowId: body.flowId })

        const decoded = PopulatedFlow.safeParse(flow)
        expect(decoded.error).toBeUndefined()
        expect(decoded.success).toBe(true)
    })

    it('reports the trigger alongside the steps so its own gaps are visible', async () => {
        const ctx = await seeded()

        const body = await generate({ ctx, prompt: 'gold price', planBody: plan({ name: 'Gold price', steps: GOLD_PRICE_PLAN }) })

        const trigger = body.steps[0]
        expect(trigger).toMatchObject({
            planStepId: null,
            pieceName: SCHEDULE,
            actionName: 'cron_expression',
            requirements: [],
            missingProperties: [],
        })
    })

    it('does not push the previous step output into a URL field', async () => {
        const ctx = await seeded()

        const body = await generate({
            ctx,
            prompt: 'two http calls',
            planBody: plan({
                name: 'Chained calls',
                steps: [
                    { id: 'first', kind: WorkflowStepKind.FETCH, summary: 'Send an HTTP request to the pricing API', service: 'web api', dependsOn: [] },
                    { id: 'second', kind: WorkflowStepKind.OUTPUT, summary: 'Send an HTTP request to the ledger API', service: 'web api', dependsOn: ['first'] },
                ],
            }),
        })
        const flow = await openInBuilder({ ctx, flowId: body.flowId })

        const second = flow.version.trigger.nextAction.nextAction
        expect(second.settings.input.url).toBeUndefined()
        expect(body.steps.find((step: { planStepId: string | null }) => step.planStepId === 'second').missingProperties).toContain('url')
    })

    it('refuses a project on another platform', async () => {
        const owner = await seeded()
        const stranger = await createTestContext(app!)

        const response = await owner.post('/v1/ai-flow-builder/generate', {
            projectId: stranger.project.id,
            prompt: 'gold price',
            plan: plan({ name: 'Gold price', steps: GOLD_PRICE_PLAN }),
        })

        expect(response?.statusCode).toBe(StatusCodes.FORBIDDEN)
    })
})

type PlanStep = {
    id: string
    kind: WorkflowStepKind
    summary: string
    service: string | null
    dependsOn: string[]
}
